### ISSUE TITLE
Implement pots API interface

### ISSUE THREAD

**Issue by maisieccino** [murraysum/monzo#3]
Monzo have added a set of [API endpoints](https://monzo.com/docs/#pots) for their new "pots" feature, it would be great to implement it in this library!

I'm a little busy with my uni work at the moment, but I'd be happy to have a go at this in about a week or so.

**Comment by murraysum** [comment]
Hello @mbellgb 

Thanks for raising the issue about supporting the new pots feature in Monzo.

I've now just pushed `v0.2.0` to ruby gems which should now handle the pots feature. You should be able to get the all of your pots for the authenticated user by:

```ruby
Monzo::Pot.all
```

https://rubygems.org/gems/monzo/versions/0.2.0

Give me a shout if you have any problems. Cheers 🙌  👍
